workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.nayifat.nayifatApp"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Clean everything
        script: |
          # Thorough cleaning
          flutter clean
          cd ios
          rm -rf Pods Podfile.lock
          rm -rf .symlinks/
          rm -rf build/
          rm -rf ~/Library/Developer/Xcode/DerivedData
          cd ..
          
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod deintegrate
          pod cache clean --all
          pod install --repo-update
          cd ..
          
      - name: Build unsigned app
        script: |
          cd ios
          
          # Create build directory
          mkdir -p build/unsigned
          
          # Force rebuild all targets
          xcodebuild clean -workspace Runner.xcworkspace -scheme Runner
          
          # Build with aggressive settings
          xcodebuild build \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build/DerivedData \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            COMPILER_INDEX_STORE_ENABLE=NO \
            SWIFT_EMIT_MODULE_INTERFACE=NO \
            DEFINES_MODULE=NO \
            APPLICATION_EXTENSION_API_ONLY=NO \
            SWIFT_INSTALL_OBJC_HEADER=NO \
            CLANG_ENABLE_MODULES=NO \
            SWIFT_COMPILATION_MODE=wholemodule \
            SWIFT_OPTIMIZATION_LEVEL="-O" \
            STRIP_SWIFT_SYMBOLS=YES \
            DEAD_CODE_STRIPPING=YES \
            ENABLE_BITCODE=NO \
            MACH_O_TYPE=staticlib \
            BUILD_LIBRARY_FOR_DISTRIBUTION=NO \
            ONLY_ACTIVE_ARCH=NO \
            DEBUG_INFORMATION_FORMAT=dwarf
            
          # Find the built app
          APP_PATH=$(find build/DerivedData -name "Runner.app" | grep Release-iphoneos)
          
          if [ -z "$APP_PATH" ]; then
            echo "Error: Could not find built app"
            exit 1
          fi
          
          # Create IPA
          echo "Creating IPA from app at: $APP_PATH"
          mkdir -p build/ios/ipa/Payload
          cp -r "$APP_PATH" build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -qr Runner.ipa Payload
          rm -rf Payload
          echo "Created unsigned IPA at build/ios/ipa/Runner.ipa"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - ios/build/DerivedData/**/Build/**/*.app
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - yamtariq@gmail.com

  ios-unsigned:
    name: iOS Unsigned Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.nayifat.nayifatApp"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up environment
        script: |
          flutter doctor -v
          
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
          
      - name: Install pods
        script: |
          cd ios
          pod install
          
      - name: Build unsigned IPA
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -archivePath build/Runner.xcarchive \
            archive
          
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist exportOptions.plist
            
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - yamtariq@gmail.com
