workflows:
  ios-workflow:
    name: iOS Debug Workflow
    environment:
      flutter: stable
      xcode: "15.0"
      cocoapods: 1.12.1
      ruby: 3.0.4
      vars:
        COCOAPODS_DISABLE_STATS: true
        SWIFT_VERSION: "5.0"
        ENABLE_BITCODE: "NO"
        DEFINES_MODULE: "YES"
        IPHONEOS_DEPLOYMENT_TARGET: "14.0"
        BUILD_LIBRARIES_FOR_DISTRIBUTION: "NO"
    scripts:
      - flutter clean
      - flutter pub get
      - gem install activesupport -v 7.0.8
      - cd ios && rm -rf Pods Podfile.lock
      - cd ios && pod install --repo-update --verbose
      - flutter build ios --debug --no-codesign