workflows:
  ios-workflow:
    name: iOS Debug Workflow
    environment:
      flutter: stable
      xcode: "15.0"
      cocoapods: 1.13.0
      ruby: 3.0.4
      vars:
        COCOAPODS_DISABLE_STATS: true
        SWIFT_VERSION: "5.0"
        ENABLE_BITCODE: "NO"
        DEFINES_MODULE: "YES"
        IPHONEOS_DEPLOYMENT_TARGET: "14.0"
        BUILD_LIBRARIES_FOR_DISTRIBUTION: "NO"
        SWIFT_INSTALL_OBJC_HEADER: "NO"
        CLANG_ENABLE_MODULES: "YES"
    scripts:
      - flutter clean
      - flutter pub get
      - cd ios && rm -rf ~/Library/Caches/CocoaPods Pods/ Podfile.lock
      - cd ios && pod cache clean --all
      - cd ios && pod repo update
      - cd ios && pod install --repo-update --verbose
      - |
        cd ios
        xcodebuild clean -workspace Runner.xcworkspace -scheme Runner -configuration Debug
        cd ..
      - flutter build ios --debug --no-codesign