workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.nayifat.nayifatApp"
    scripts:
      - name: Clean and Setup
        script: |
          flutter clean
          flutter pub get
          
      - name: Remove iOS directory
        script: |
          rm -rf ios
          
      - name: Create fresh iOS project
        script: |
          flutter create --platforms ios .
          flutter pub get
          
      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          rm -rf Pods Podfile.lock
          pod cache clean --all
          pod install --repo-update
          cd ..
          
      - name: Update build settings
        script: |
          cd ios
          /usr/libexec/PlistBuddy -c "Set :SWIFT_VERSION 5.0" Runner/Info.plist
          
          # Update project.pbxproj settings
          sed -i '' 's/SWIFT_OPTIMIZATION_LEVEL = "-Onone";/SWIFT_OPTIMIZATION_LEVEL = "-O";/g' Runner.xcodeproj/project.pbxproj
          sed -i '' 's/SWIFT_COMPILATION_MODE = "singlefile";/SWIFT_COMPILATION_MODE = "wholemodule";/g' Runner.xcodeproj/project.pbxproj
          cd ..
          
      - name: Build unsigned IPA
        script: |
          flutter build ipa --release --no-codesign --no-tree-shake-icons
          
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      email:
        recipients:
          - yamtariq@gmail.com
