workflows:
  ios-workflow:
    name: iOS Debug Workflow
    environment:
      flutter: stable
      xcode: "15.0"
      # Using CocoaPods 1.11.x or 1.16.x typically works;
      # if you see gem errors, try 1.11.3 or 1.16.0
      cocoapods: 1.11.3
      ruby: 3.0.4
      vars:
        COCOAPODS_DISABLE_STATS: true
        SWIFT_VERSION: "5.0"
        ENABLE_BITCODE: "NO"
        DEFINES_MODULE: "YES"
        IPHONEOS_DEPLOYMENT_TARGET: "14.0"
        BUILD_LIBRARIES_FOR_DISTRIBUTION: "NO"
        SWIFT_INSTALL_OBJC_HEADER: "NO"
        CLANG_ENABLE_MODULES: "YES"
    scripts:
      - flutter clean
      - flutter pub get
      - |
        cd ios
        rm -rf ~/Library/Caches/CocoaPods Pods Podfile.lock
        pod repo update
        pod install --repo-update --verbose
      - |
        cd ios
        xcodebuild clean -workspace Runner.xcworkspace -scheme Runner -configuration Debug
        cd ..
      - flutter build ios --debug --no-codesign
