workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.nayifat.nayifatApp"
    scripts:
      - name: Set up
        script: |
          flutter clean
          flutter pub get
          
      - name: Remove existing iOS directory
        script: |
          rm -rf ios
          
      - name: Create fresh iOS build
        script: |
          flutter create --platforms ios .
          flutter pub get
          
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
          
      - name: Build unsigned IPA
        script: |
          cd ios
          xcodebuild clean archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM=""
            
          mkdir -p build/ios/ipa/Payload
          cp -r build/Runner.xcarchive/Products/Applications/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -qr Runner.ipa Payload
          rm -rf Payload
          
    artifacts:
      - build/ios/ipa/*.ipa
      - ios/build/**/*.app
      
    publishing:
      email:
        recipients:
          - yamtariq@gmail.com
