workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.nayifat.nayifatApp"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Clean build
        script: |
          # Clean everything
          flutter clean
          cd ios
          rm -rf Pods Podfile.lock
          rm -rf .symlinks/
          rm -rf build/
          cd ..
          
      - name: Get dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..
          
      - name: Configure projects
        script: |
          cd ios
          
          # Configure Runner project
          ruby << 'EOF'
          require 'xcodeproj'
          
          # Configure Runner project
          runner_project = Xcodeproj::Project.open('Runner.xcodeproj')
          runner_project.targets.each do |target|
            if target.name == 'Runner'
              target.build_configurations.each do |config|
                config.build_settings['SWIFT_EMIT_MODULE_INTERFACE'] = 'NO'
                config.build_settings['DEFINES_MODULE'] = 'NO'
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
                config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
              end
            end
          end
          runner_project.save
          
          # Configure Pods project
          pods_project = Xcodeproj::Project.open('Pods/Pods.xcodeproj')
          pods_project.targets.each do |target|
            target.build_configurations.each do |config|
              if config.build_settings['SWIFT_VERSION']
                config.build_settings['SWIFT_EMIT_MODULE_INTERFACE'] = 'NO'
                config.build_settings['DEFINES_MODULE'] = 'YES'
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
                config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
              end
            end
          end
          pods_project.save
          EOF
          
          cd ..
          
      - name: Build unsigned app
        script: |
          cd ios
          
          # Create build directory
          mkdir -p build/unsigned
          
          # Build unsigned app with legacy build system
          xcodebuild \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build/DerivedData \
            -UseModernBuildSystem=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            COMPILER_INDEX_STORE_ENABLE=NO \
            STRIP_INSTALLED_PRODUCT=NO \
            SWIFT_EMIT_MODULE_INTERFACE=NO \
            DEFINES_MODULE=NO \
            SWIFT_COMPILATION_MODE=wholemodule \
            OTHER_SWIFT_FLAGS="-no-verify-emitted-module-interface"
            
          # Find the built app
          APP_PATH=$(find build/DerivedData -name "Runner.app" | grep Release-iphoneos)
          
          if [ -z "$APP_PATH" ]; then
            echo "Error: Could not find built app"
            exit 1
          fi
          
          # Create IPA
          echo "Creating IPA from app at: $APP_PATH"
          mkdir -p build/ios/ipa/Payload
          cp -r "$APP_PATH" build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -qr Runner.ipa Payload
          rm -rf Payload
          echo "Created unsigned IPA at build/ios/ipa/Runner.ipa"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - ios/build/DerivedData/**/Build/**/*.app
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - yamtariq@gmail.com

  ios-unsigned:
    name: iOS Unsigned Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.nayifat.nayifatApp"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up environment
        script: |
          flutter doctor -v
          
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
          
      - name: Install pods
        script: |
          cd ios
          pod install
          
      - name: Build unsigned IPA
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -archivePath build/Runner.xcarchive \
            archive
          
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist exportOptions.plist
            
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - yamtariq@gmail.com
