wworkflows:
  ios-build:
    name: iOS Build
    scripts:
      - echo "Updating CocoaPods"
      - sudo gem install cocoapods -v 1.13.0
      - echo "Cleaning Flutter project"
      - flutter clean
      - echo "Installing pods"
      - cd ios && pod install && cd ..
      - echo "Building iOS app"
      - flutter build ios --debug --no-codesign
