workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.13.0
      vars:
        BUNDLE_ID: "com.nayifat.app2025"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    cache:
      cache_paths:
        - ~/.pub-cache
        - vendor/bundle
    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Setup iOS project 💡
        script: |
          flutter create . --platforms=ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod repo update
          pod cache clean --all
          rm -rf Pods
          rm -rf Podfile.lock
          pod install
      - name: Build iOS
        script: | 
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - developers@nayifat.com
        notify:
          success: true
          failure: true
