workflows:
  ios-workflow:
    name: iOS Debug Workflow
    environment:
      flutter: stable
      xcode: "15.0"
      cocoapods: 1.12.1
      vars:
        COCOAPODS_DISABLE_STATS: true
        SWIFT_VERSION: "5.0"
        ENABLE_BITCODE: "NO"
        DEFINES_MODULE: "YES"
        IPHONEOS_DEPLOYMENT_TARGET: "14.0"
    scripts:
      - flutter clean
      - flutter pub get
      - cd ios && rm -rf Pods/ Podfile.lock
      - cd ios && pod install --repo-update
      - flutter build ios --debug --no-codesign