workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.nayifat.nayifatApp"
    scripts:
      - name: Clean and Setup
        script: |
          flutter clean
          flutter pub get
          
      - name: Remove iOS directory
        script: |
          rm -rf ios
          
      - name: Create fresh iOS project
        script: |
          flutter create --platforms ios .
          flutter pub get
          
      - name: Update Podfile
        script: |
          cd ios
          echo "platform :ios, '14.0'
          
          # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
          ENV['COCOAPODS_DISABLE_STATS'] = 'true'
          
          source 'https://cdn.cocoapods.org/'
          
          project 'Runner', {
            'Debug' => :debug,
            'Profile' => :release,
            'Release' => :release,
          }
          
          def flutter_root
            generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
            unless File.exist?(generated_xcode_build_settings_path)
              raise \"#{generated_xcode_build_settings_path} must exist. If you are running pod install manually, make sure flutter pub get is executed first\"
            end
          
            File.foreach(generated_xcode_build_settings_path) do |line|
              matches = line.match(/FLUTTER_ROOT\=(.*)/)
              return matches[1].strip if matches
            end
            raise \"FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}\"
          end
          
          require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
          
          flutter_ios_podfile_setup
          
          target 'Runner' do
            use_frameworks!
            use_modular_headers!
            
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
            
            # Add specific pod dependencies
            pod 'DKImagePickerController', '~> 4.3.4'
            pod 'PhoneNumberKit', '~> 3.7', :modular_headers => true
          end
          
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
              target.build_configurations.each do |config|
                # Basic settings
                config.build_settings['ENABLE_BITCODE'] = 'NO'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
                
                # Module settings
                config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
                config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
                config.build_settings['DEFINES_MODULE'] = 'YES'
                config.build_settings['SWIFT_INSTALL_OBJC_HEADER'] = 'NO'
                
                # Swift settings
                config.build_settings['SWIFT_VERSION'] = '5.0'
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
                config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
                
                # Additional settings for DKImagePickerController
                config.build_settings['ENABLE_MODULES'] = 'YES'
                config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
                
                # Handle arm64 for simulators
                if config.build_settings['PLATFORM_NAME'] == 'iphonesimulator'
                  config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
                end
              end
            end
          end" > Podfile
          
      - name: Install Pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --repo-update
          cd ..
          
      - name: Update build settings
        script: |
          cd ios
          /usr/libexec/PlistBuddy -c "Set :SWIFT_VERSION 5.0" Runner/Info.plist
          
          # Update project.pbxproj settings
          sed -i '' 's/SWIFT_OPTIMIZATION_LEVEL = "-Onone";/SWIFT_OPTIMIZATION_LEVEL = "-O";/g' Runner.xcodeproj/project.pbxproj
          sed -i '' 's/SWIFT_COMPILATION_MODE = "singlefile";/SWIFT_COMPILATION_MODE = "wholemodule";/g' Runner.xcodeproj/project.pbxproj
          cd ..
          
      - name: Build unsigned IPA
        script: |
          flutter build ipa --release --no-codesign --no-tree-shake-icons
          
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      email:
        recipients:
          - yamtariq@gmail.com
