workflows:
  ios-workflow:
    name: iOS Workflow final 3
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.nayifat.nayifatApp"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up environment
        script: |
          flutter doctor -v
          flutter --version
          xcodebuild -version
          
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
          
      - name: Install pods
        script: |
          cd ios
          pod install
          
      - name: Build unsigned IPA
        script: |
          cd ios
          
          # Update build settings
          /usr/libexec/PlistBuddy -c "Add :buildSettings:SWIFT_EMIT_MODULE_INTERFACE string NO" Runner.xcodeproj/project.pbxproj
          /usr/libexec/PlistBuddy -c "Add :buildSettings:SWIFT_OPTIMIZATION_LEVEL string -Onone" Runner.xcodeproj/project.pbxproj
          
          # Create archive
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_EMIT_MODULE_INTERFACE=NO \
            SWIFT_OPTIMIZATION_LEVEL="-Onone" \
            DEVELOPMENT_TEAM="" \
            -archivePath build/Runner.xcarchive \
            clean archive
          
          # Create IPA using ad-hoc method
          mkdir -p build/ios/ipa
          
          # Create a temporary exportOptions.plist for this specific export
          cat > exportOptionsTemp.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>compileBitcode</key>
              <false/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <false/>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <false/>
              <key>teamID</key>
              <string></string>
          </dict>
          </plist>
          EOF
          
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist exportOptionsTemp.plist \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM=""
            
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - yamtariq@gmail.com

  ios-unsigned:
    name: iOS Unsigned Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.nayifat.nayifatApp"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up environment
        script: |
          flutter doctor -v
          
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
          
      - name: Install pods
        script: |
          cd ios
          pod install
          
      - name: Build unsigned IPA
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -archivePath build/Runner.xcarchive \
            archive
          
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist exportOptions.plist
            
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - yamtariq@gmail.com
