workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      ruby: 3.2.2
      cocoapods: 1.12.1
      vars:
        BUNDLE_ID: "com.nayifat.app2025"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    cache:
      cache_paths:
        - ~/.pub-cache
        - vendor/bundle
    scripts:
      - name: Set up environment 💡
        script: |
          flutter doctor -v
          flutter --version
          xcodebuild -version
          gem update --system
          gem install bundler
          gem install cocoapods -v 1.12.1
          pod --version
          ruby --version
      - name: Clean and prepare 💡
        script: |
          echo "Current directory: $PWD"
          rm -rf build
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Flutter.podspec
          flutter clean
          flutter pub get
      - name: Setup iOS project 💡
        script: |
          flutter create . --platforms=ios
          cd ios
          rm -f Podfile
          rm -f Podfile.lock
          pod cache clean --all
          gem uninstall cocoapods-core
          gem install cocoapods-core -v 1.12.1
          cd ..
          flutter pub get
      - name: Install CocoaPods dependencies 💡
        script: |
          cd ios
          pod repo update
          rm -rf Pods
          rm -f Podfile.lock
          flutter pub get
          pod install --verbose --repo-update --no-repo-update
          cd ..
      - name: Build iOS 💡
        script: | 
          flutter build ios --debug --no-codesign --verbose
    artifacts:
      - build/ios/iphoneos/Runner.app
      - ios/Pods/Manifest.lock
      - ios/Podfile.lock
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - ios/build/Runner.build/Debug-iphoneos/Runner.build/build-state.dat
    publishing:
      email:
        recipients:
          - yamtariq@gmail.com
        notify:
          success: true
          failure: true
