workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: 3.16.9
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.nayifat.nayifatApp"
    scripts:
      - name: Build Preparation
        script: |
          flutter clean
          flutter pub get
          
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
          
      - name: Set iOS deployment target
        script: |
          cd ios
          LC_ALL=C find . -type f -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 12.0/IPHONEOS_DEPLOYMENT_TARGET = 14.0/g' {} +
          cd ..
          
      - name: Build unsigned IPA
        script: |
          flutter build ipa --no-codesign --no-tree-shake-icons --dart-define=BUILD_MODE=production
          
    artifacts:
      - build/ios/ipa/*.ipa
      
    publishing:
      email:
        recipients:
          - yamtariq@gmail.com
