name: nayifat_app_2025_new
description: Nayifat App 2025

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0
  circle_nav_bar: ^2.0.1
  device_info_plus: ^9.1.2
  font_awesome_flutter: ^10.5.0
  flutter_svg: ^2.0.9
  flutter_animate: ^4.5.0
  hijri: ^3.0.0
  hijri_picker:
    git:
      url: https://github.com/ahmedoid/hijri_picker
      ref: master
  http: ^1.1.0
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  local_auth: ^2.1.7
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  video_player: ^2.8.2
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  crypto: ^3.0.6
  logging: ^1.2.0
  google_maps_flutter: ^2.10.0
  lottie: ^2.7.0
  file_picker: ^8.1.7
  provider: ^6.1.1
  awesome_notifications: ^0.8.2
  path_provider: ^2.1.5
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  mockito: ^5.4.4
  build_runner: ^2.4.8
  test: ^1.24.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500

  assets:
    - assets/images/
    - assets/videos/
    - assets/fonts/
    - assets/animations/
    - assets/docs/
    - assets/icons/