//
//  Generated file. Do not edit.
//  This file is generated by Flutter and lists the plugins used in your project.
//
import Flutter
import UIKit

func RegisterGeneratedPlugins(registry: FlutterPluginRegistry) {
  // Plugin registration goes here.
  // For example:
  // FLTFirebaseCorePlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseCorePlugin"))
}

@objc class GeneratedPluginRegistrant: NSObject {
    @objc static func register(with registry: FlutterPluginRegistry) {
        RegisterGeneratedPlugins(registry: registry)
    }
} 