name: Build iOS Flutter App

on: push

jobs:
  build_ios:
    runs-on: macos-13
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: stable
        cache: true
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.3.1'

    - name: Setup Ruby and CocoaPods
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    
    - name: Install CocoaPods
      run: |
        gem install cocoapods -v 1.15.2
        pod --version

    - name: Flutter Setup
      run: |
        flutter doctor -v
        flutter --version
        
    - name: Clean and Setup iOS
      run: |
        flutter clean
        flutter pub get
        cd ios
        rm -rf Pods Podfile.lock
        rm -rf .symlinks/
        cd ..
        
    - name: Generate iOS Files
      run: |
        flutter pub get
        cd ios
        pod cache clean --all
        rm -rf ~/Library/Caches/CocoaPods
        pod deintegrate
        pod setup --verbose
        pod install --verbose
        cd ..
        
    - name: Prepare Flutter
      run: |
        flutter precache --ios --force
        flutter pub get --verbose
        
    - name: Build iOS
      run: |
        export NO_FLIPPER=1
        cd ios
        pod install --repo-update
        cd ..
        flutter build ios --release --no-codesign --verbose
      env:
        DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer
