name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # (Removed bridging-header overrides)
      # Update Podfile to add use_frameworks!
      - name: Update Podfile
        run: |
          cd ios
          echo "install! 'cocoapods', :disable_input_output_paths => true" > Podfile.new
          echo "" >> Podfile.new
          echo "use_frameworks!" >> Podfile.new
          cat Podfile >> Podfile.new
          echo "" >> Podfile.new
          echo "post_install do |installer|" >> Podfile.new
          echo "  installer.pods_project.targets.each do |target|" >> Podfile.new
          echo "    target.build_configurations.each do |config|" >> Podfile.new
          echo "      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'" >> Podfile.new
          echo "    end" >> Podfile.new
          echo "  end" >> Podfile.new
          echo "end" >> Podfile.new
          mv Podfile.new Podfile


      - name: Clean iOS
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          cd ..
          flutter clean

      - name: Get Flutter dependencies
        run: flutter pub get

      - run: gem install cocoapods

      - name: Pod Install
        run: |
          cd ios
          pod install --repo-update

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
