name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Configure Xcode build settings
      - name: Configure Build Settings
        run: |
          cd ios
          echo "SWIFT_OBJC_BRIDGING_HEADER=''" >> Flutter/Release.xcconfig
          echo "SWIFT_OBJC_INTERFACE_HEADER_NAME=''" >> Flutter/Release.xcconfig
          echo "DEFINES_MODULE=NO" >> Flutter/Release.xcconfig
          echo "CLANG_ENABLE_MODULES=NO" >> Flutter/Release.xcconfig

      # Update Podfile
      - name: Update Podfile
        run: |
          cd ios
          echo "install! 'cocoapods', :disable_input_output_paths => true" > Podfile.new
          echo "" >> Podfile.new
          echo "use_frameworks!" >> Podfile.new
          cat Podfile >> Podfile.new
          mv Podfile.new Podfile

      # Clean iOS but keep Generated.xcconfig intact by running flutter clean last
      - name: Clean iOS
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          cd ..
          flutter clean

      # Re-generate Generated.xcconfig
      - name: Get Flutter dependencies
        run: flutter pub get

      # Install CocoaPods
      - run: gem install cocoapods

      # Install and update pods
      - name: Pod Install
        run: |
          cd ios
          pod install --repo-update

      # Build iOS
      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
