name: iOS-ipa-build
on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - run: flutter pub get
      
      - name: Ensure Generated.xcconfig exists
        run: |
          if [ ! -f ios/Flutter/Generated.xcconfig ]; then
            mkdir -p ios/Flutter
            echo "// Generated.xcconfig" > ios/Flutter/Generated.xcconfig
          fi
          
      # Add this new step to configure build settings
      - name: Configure iOS build settings
        run: |
          echo "SWIFT_VERSION=5.0" >> ios/Flutter/Release.xcconfig
          echo "CLANG_ENABLE_MODULES=NO" >> ios/Flutter/Release.xcconfig
          echo "DEFINES_MODULE=NO" >> ios/Flutter/Release.xcconfig
          
      - name: Clean iOS build
        run: |
          rm -rf Podfile.lock Pods/ .symlinks Flutter/Flutter.podspec
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
        working-directory: ios
        
      - run: gem install cocoapods
      
      # Modify Podfile configuration
      - name: Update Podfile
        run: |
          echo "use_frameworks! :linkage => :static" > Podfile.tmp
          cat Podfile >> Podfile.tmp
          mv Podfile.tmp Podfile
        working-directory: ios
        
      - run: pod repo update
        working-directory: ios
        
      - run: pod install --repo-update
        working-directory: ios
        
      - run: flutter build ios --release --no-codesign
      
      - run: mkdir Payload
        working-directory: build/ios/iphoneos
        
      - run: mv Runner.app Payload
        working-directory: build/ios/iphoneos
        
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos
        
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
