name: iOS Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate iOS directory
        run: flutter create --platforms=ios .

      - name: Set iOS Deployment Target
        run: sed -i '' 's/platform :ios, '9.0'/platform :ios, '14.0'/g' ios/Podfile

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
          cd ..

      - name: Build iOS (No Code Signing)
        run: flutter build ipa --no-codesign

      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: Unsigned-iOS-IPA
          path: build/ios/ipa/*.ipa
