name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    env:
      FLUTTER_ROOT: ${{ github.workspace }}/flutter
      DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

    steps:
      - uses: actions/checkout@v4  # Updated from v3

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Flutter Setup
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.27.1'
          architecture: x64

      - name: Install CocoaPods
        run: |
          sudo gem uninstall cocoapods -a --force
          sudo gem install cocoapods -v 1.14.3
          pod setup --verbose

      - name: Clean Workspace
        run: |
          flutter clean
          rm -rf ios/Podfile.lock ios/Pods

      - name: Get Packages
        run: flutter pub get

      - name: Install Pods
        working-directory: ios
        run: |
          pod repo update
          pod install --repo-update --verbose

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign \
            --dart-define=CI=true \
            --target-platform ios-arm64

      - name: Create IPA
        working-directory: build/ios/iphoneos
        run: |
          mkdir Payload
          mv Runner.app Payload/
          zip -qr FlutterIpaExport.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Critical update from v3
        with:
          name: ios-build
          path: build/ios/iphoneos/FlutterIpaExport.ipa
