name: Build iOS Flutter App

on: push

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Get Dependencies
        run: flutter pub get

      - name: Flutter Clean
        run: flutter clean

      - name: Setup Flutter
        run: flutter pub get ; flutter precache

      - name: Clean Pod Cache
        run: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ~/.cocoapods/

      - name: Update CocoaPods
        run: sudo gem install cocoapods -v 1.14.2

      - name: Repo Update
        run: pod repo update

      - name: Pod Install
        run: cd ios ; rm -f Podfile.lock ; pod install ; cd ..

      - name: Build iOS App (no codesign)
        run: flutter build ios --release --no-codesign
