name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable-3.27.1-x64
      DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

    steps:
      - uses: actions/checkout@v4

      - name: Force Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: /Users/runner/hostedtoolcache/flutter/stable-3.27.1-x64
          key: flutter-macos-stable-${{ runner.os }}-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            flutter-macos-stable-${{ runner.os }}-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: stable

      - name: Install Exact CocoaPods Version
        run: |
          sudo gem install cocoapods -v 1.14.3 --conservative
          pod setup --verbose

      - name: Clean Environment
        run: |
          flutter clean
          rm -rf ios/Podfile.lock ios/Pods

      - name: Install Dependencies
        run: flutter pub get

      - name: Pod Install with Retry
        working-directory: ios
        run: |
          pod repo update
          pod install --verbose

      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        working-directory: build/ios/iphoneos
        run: |
          mkdir Payload
          mv Runner.app Payload/
          zip -qr app.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/app.ipa

      - name: Generate Flutter Files
        run: |
          flutter clean
          flutter pub get
          # Force regeneration of critical iOS files
          touch ios/Runner.xcodeproj/project.pbxproj

      - name: Pod Install
        working-directory: ios
        run: |
          pod install --verbose
        env:
          FLUTTER_ROOT: ${{ github.workspace }}/flutter