name: Build iOS Flutter App

on: push

jobs:
  build_ios:
    runs-on: macos-13
    env:
      FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable-3.27.1-x64

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: stable
        architecture: x64

    - name: Setup Ruby and CocoaPods
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        bundler: '2.4.21'
        
    - name: Install Latest CocoaPods
      run: sudo gem install cocoapods -v 1.15.2

    - name: Clean Workspace and iOS Build
      run: |
        flutter clean
        cd ios
        rm -rf Pods Podfile.lock
        rm -rf .symlinks/
        cd ..

    - name: Get Dependencies
      run: |
        flutter pub get
        flutter pub cache repair

    - name: Pod Setup and Install
      working-directory: ios
      run: |
        pod deintegrate
        pod setup
        pod install --repo-update --clean-install

    - name: Build iOS App
      run: |
        flutter precache --ios
        flutter build ios --release --no-codesign --dart-define=CI=true
      env:
        DEVELOPER_DIR: /Applications/Xcode_14.3.1.app
