name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    env:
      FLUTTER_ROOT: ${{ github.workspace }}/flutter
      DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

    steps:
      - uses: actions/checkout@v3

      # 1. Force Xcode 15.4 setup
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      # 2. Flutter setup matching your local version
      - name: Flutter Setup
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.27.1'
          architecture: x64

      # 3. CocoaPods setup with exact version
      - name: Install CocoaPods
        run: |
          sudo gem uninstall cocoapods -a --force
          sudo gem install cocoapods -v 1.14.3
          pod setup --verbose

      # 4. Full clean cycle
      - name: Clean Workspace
        run: |
          flutter clean
          rm -rf ios/Podfile.lock ios/Pods

      # 5. Get dependencies
      - name: Get Packages
        run: flutter pub get

      # 6. Pod installation with CI optimizations
      - name: Install Pods
        working-directory: ios
        run: |
          pod repo update
          pod install --repo-update --verbose

      # 7. Build with architecture fixes
      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign \
            --dart-define=CI=true \
            --target-platform ios-arm64

      # 8. Package IPA
      - name: Create IPA
        working-directory: build/ios/iphoneos
        run: |
          mkdir Payload
          mv Runner.app Payload/
          zip -qr FlutterIpaExport.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos/FlutterIpaExport.ipa