name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Force Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: stable
          cache: true

      - name: Install Exact CocoaPods Version
        run: |
          sudo gem install cocoapods -v 1.14.3 --conservative
          pod setup

      - name: Clean Environment
        run: |
          flutter clean
          rm -rf ios/Podfile.lock ios/Pods ios/Flutter/Flutter.framework ios/Flutter/Flutter.podspec

      - name: Install Dependencies
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Pod Install with Retry
        working-directory: ios
        run: |
          pod repo update
          pod deintegrate
          pod cache clean --all
          rm -rf Pods/
          pod install --verbose

      - name: Build iOS App
        run: |
          flutter precache --ios
          flutter build ios --release --no-codesign

      - name: Create IPA
        working-directory: build/ios/iphoneos
        run: |
          mkdir Payload
          mv Runner.app Payload/
          zip -qr app.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/app.ipa